universe    =  vanilla
arguments   =  $(sample)
executable  =  /afs/cern.ch/work/d/druini/public/hepaccelerate/submission/submit_condor.sh
log         =  /afs/cern.ch/work/d/druini/public/hepaccelerate/condor_output/$(sample).log
error       =  /afs/cern.ch/work/d/druini/public/hepaccelerate/condor_output/$(sample).err
output      =  /afs/cern.ch/work/d/druini/public/hepaccelerate/condor_output/$(sample).out
#####initialdir  = /eos/home-a/algomez/tmpFiles/hepaccelerate//2017_TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8
#####should_transfer_files = YES
####when_to_transfer_output = ON_EXIT
#####transfer_input_files = out_TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.json
getenv      =  True
####requirements = (OpSysAndVer =?= "SLCern6")
+JobFlavour = "testmatch"
queue sample from /afs/cern.ch/work/d/druini/public/hepaccelerate/datasets/algomez/twoSamples.txt
