year        =  2017
universe    =  vanilla
arguments   =  $(sample) $(year)
executable  =  $ENV(PWD)/submission/submit_condor.sh
log         =  $ENV(PWD)/condor_output/$(sample)_$(ClusterId)_$(ProcId)_$(year).log
error       =  $ENV(PWD)/condor_output/$(sample)_$(ClusterId)_$(ProcId)_$(year).err
output      =  $ENV(PWD)/condor_output/$(sample)_$(ClusterId)_$(ProcId)_$(year).out
getenv      =  True
+JobFlavour =  "nextweek"
queue sample from $ENV(PWD)/submission/allSamples_$(year).txt
